/* Generated By:JJTree: Do not edit this line. ASTArrayAcc.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTArrayAcc extends ASTVariableUse {
  public ASTVariableUse getBase() {
    SimpleNode n;
    for (n = this; !(n instanceof ASTVariableUse); n = ((ASTArrayAcc) n).getReferenz()) ;
    return (ASTVariableUse) n;
  }
  // service
  public ASTExpression getReferenz() { return (ASTExpression) jjtGetChild(0); }
  public ASTExpression getIndex() { return (ASTExpression) jjtGetChild(1); }

  public ASTArrayAcc(int id) {
    super(id);
  }

  public ASTArrayAcc(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e80b45dd970549df1bee4dd8e245b46 (do not edit this line) */
