/* Generated By:JJTree: Do not edit this line. ASTAttribute.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTAttribute extends ASTVariableDecl {
  protected boolean isPrivate = false;
  // getter and setter
  public boolean isPrivate() {
    return isPrivate;
  }
  public void setPrivate(boolean aPrivate) {
    isPrivate = aPrivate;
  }


  public ASTAttribute(int id) {
    super(id);
  }

  public ASTAttribute(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4705858dae5b942abeff767877e93d6a (do not edit this line) */
