/* Generated By:JJTree: Do not edit this line. ASTArrayType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTArrayType extends ASTType {
  protected int dimension = 0;

  public int getDimension() { return dimension; }
  public int incDimension() { return ++dimension; }

  public ASTType getBaseType() { return (ASTType) jjtGetChild(0); }


  public ASTArrayType(int id) {
    super(id);
  }

  public ASTArrayType(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=86042c7ac08156f6ca216f076424c98d (do not edit this line) */
