/* Generated By:JJTree: Do not edit this line. ASTAssignment.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTAssignment extends ASTExpression {
  public int size() { return jjtGetNumChildren(); }
  public ASTExpression getOperand(int i) {
    return (ASTExpression) jjtGetChild(i);
  }

  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c0ed770260e3c324da9d5063cc76b306 (do not edit this line) */
