/* Generated By:JJTree: Do not edit this line. ASTBlock.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTBlock extends SimpleNode {
  public int size() { return jjtGetNumChildren(); }

  public ASTBlock(int id) {
    super(id);
  }

  public ASTBlock(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=17ce603cfc46f46a3b0122d8198b7bc2 (do not edit this line) */
