/* Generated By:JJTree: Do not edit this line. ASTConstructor.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTConstructor extends ASTMethod {
  public ASTConstructor(int id) {
    super(id);
  }

  public ASTConstructor(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2309a982b1dce3812226fb8eb9de2a55 (do not edit this line) */
