/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTClass extends ASTUserDefined {

  public ASTClass(int id) {
    super(id);
  }
  public ASTClass(STMJ p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=eae8daf5466ff753fbff068e4edbb54a (do not edit this line) */
