/* Generated By:JJTree: Do not edit this line. ASTDeref.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTDeref extends ASTExpression {
  // Access to kids
  public ASTExpression getReference() { return (ASTExpression) jjtGetChild(0); }
  public ASTExpression getMethodOrVariable() { return (ASTExpression) jjtGetChild(1); }
  public ASTMethodCall getMethodCall() {
    if (isMethodCall()) return (ASTMethodCall) jjtGetChild(1);
    else return null;
  }
  public ASTVariableUse getVariableUse() {
    if (!isMethodCall()) return (ASTVariableUse) jjtGetChild(1);
    else return null;
  }
  // service
  public boolean isMethodCall() { return jjtGetChild(1) instanceof ASTMethodCall; }

  public ASTDeref(int id) {
    super(id);
  }

  public ASTDeref(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec1a149f2bde067ea6b4c8ca085752aa (do not edit this line) */
