/* Generated By:JJTree: Do not edit this line. ASTDoWhile.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTDoWhile extends ASTStatement {
  public ASTExpression getCondition() {
    return (ASTExpression) jjtGetChild(1);
  }
  public ASTStatement getStatement() {
    return (ASTStatement) jjtGetChild(0);
  }

  public ASTDoWhile(int id) {
    super(id);
  }
  public ASTDoWhile(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a7c04b2ffd284e0482f2089e6deb6d4 (do not edit this line) */
