/* Generated By:JJTree: Do not edit this line. ASTEmptyStatement.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTEmptyStatement extends SimpleNode {
  public ASTEmptyStatement(int id) {
    super(id);
  }

  public ASTEmptyStatement(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05d62625bea2fee1f3713733655df220 (do not edit this line) */
