/* Generated By:JJTree: Do not edit this line. ASTExprStatement.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTExprStatement extends ASTStatement {

  public ASTExpression getExpression() {
    return (ASTExpression) jjtGetChild(0);
  }

  public ASTExprStatement(int id) {
    super(id);
  }
  public ASTExprStatement(STMJ p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=34a5df41d963f8a476a88d279513d848 (do not edit this line) */
