/* Generated By:JJTree: Do not edit this line. ASTIf.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTIf extends ASTStatement {
  public boolean hasElse() { return jjtGetNumChildren()>2; }
  public ASTExpression getCondition() {
    return (ASTExpression) jjtGetChild(0);
  }
  public ASTStatement getIfStatement() {
    return (ASTStatement) jjtGetChild(1);
  }
  public ASTStatement getElseStatement() {
    return hasElse() ? (ASTStatement) jjtGetChild(2) : null ;
  }

  public ASTIf(int id) {
    super(id);
  }
  public ASTIf(STMJ p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=8aa5cbfb36809fc80b6f135e119fc142 (do not edit this line) */
