/* Generated By:JJTree: Do not edit this line. ASTLogical.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

import java.util.LinkedList;
import java.util.List;

public
class ASTLogical extends ASTExpression {
  protected List<String> operators = new LinkedList<String>();

  public int size() { return jjtGetNumChildren(); }
  public ASTExpression getOperand(int i) { return (ASTExpression) jjtGetChild(i); }
  public String getOperator(int i) { return operators.get(i); }
  public void addOperator(String op) { operators.add(op); }

  public ASTLogical(int id) {
    super(id);
  }
  public ASTLogical(STMJ p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=7bafa94ec722195dd7d0717f3ecc1698 (do not edit this line) */
