/* Generated By:JJTree: Do not edit this line. ASTMethodCall.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

import java.util.LinkedList;
import java.util.List;

public
class ASTMethodCall extends ASTExpression {
  String name;
  ASTExpression deref = null;

  public void setDeref(Node n) { deref = (ASTExpression) n; }
  public ASTExpression getDeref() {
    return deref;
  }

  public String getName() {
    return name;
  }
  public void setName(String name) { this.name = name; }
  public int getNumberArguments() { return jjtGetNumChildren(); }
  public ASTExpression getArgument(int i) {
    return (ASTExpression) jjtGetChild(i);
  }


  public ASTMethodCall(int id) {
    super(id);
  }

  public ASTMethodCall(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1cd16360a5a517f084078b625d70399 (do not edit this line) */
