/* Generated By:JJTree: Do not edit this line. ASTMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTMethod extends SimpleNode {
  protected String name;
  protected boolean isPrivate = false;
  protected boolean isStatic = false;

  protected boolean isClassMethod() { return isStatic; }

  public int getNumberParameter() { return jjtGetNumChildren()-1; }
  public ASTParameter getParameter(int i) { return (ASTParameter) jjtGetChild(i+1); }
  public ASTType getASTReturnType() {
    return (ASTType) jjtGetChild(0);
  }

  public void setName(String name) {
    this.name = name;
  }
  public boolean isPrivate() {
    return isPrivate;
  }
  public void setPrivate(boolean aPrivate) {
    isPrivate = aPrivate;
  }
  public boolean isStatic() {
    return isStatic;
  }
  public void setStatic(boolean aStatic) {
    isStatic = aStatic;
  }
  public String getName() { return name; }


  public ASTMethod(int id) {
    super(id);
  }
  public ASTMethod(STMJ p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=0805d0bc749b7e53649cd3694bc13ff3 (do not edit this line) */
