/* Generated By:JJTree: Do not edit this line. ASTMethodBlock.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTMethodBlock extends SimpleNode {
  public ASTMethodBlock(int id) {
    super(id);
  }

  public ASTMethodBlock(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a14e60bf71049fe2035cdc204c55227 (do not edit this line) */
