/* Generated By:JJTree: Do not edit this line. ASTNewArray.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTNewArray extends ASTExpression {
  protected int resDim = 1;
  protected int unresDim;

  public ASTType getBType() { return (ASTType) jjtGetChild(0); }
  public String getBName() { return getBType().toString(); }

  public int getDimension() { return resDim + unresDim; }
  public int getResDim() { return resDim; }
  public int getUnresDim() { return unresDim; }
  public void incResDim() { resDim++; }
  public void incUnresDim() { unresDim++; }

  public ASTNewArray(int id) {
    super(id);
  }
  public ASTNewArray(STMJ p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=75786c77e53b7b403c5659b0b55ff16b (do not edit this line) */
