/* Generated By:JJTree: Do not edit this line. ASTNot.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTNot extends ASTExpression {
  public ASTExpression getOperand() { return (ASTExpression) jjtGetChild(0); }

  public ASTNot(int id) {
    super(id);
  }

  public ASTNot(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c6eed839e73f9cfdc0befb4785899a2 (do not edit this line) */
