/* Generated By:JJTree: Do not edit this line. ASTParameter.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTParameter extends ASTVariableDecl {
  public ASTParameter(int id) {
    super(id);
  }

  public ASTParameter(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3118a8f7173d0c9be59c8b04f2dcd9c7 (do not edit this line) */
