/* Generated By:JJTree: Do not edit this line. ASTPre.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTPre extends ASTExpression {
  protected String operator;

  public ASTExpression getOperand() { return (ASTExpression) jjtGetChild(0); }
  public String getOperator() { return operator; }
  public void setOperator(String op) { operator = op; }

  public ASTPre(int id) {
    super(id);
  }

  public ASTPre(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae2474779f78dc113ee92898e771db34 (do not edit this line) */
