/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTReturn extends ASTStatement {
  public boolean hasReturnValue() { return jjtGetNumChildren()>0; }
  public ASTExpression getReturnExpression() {
    if (hasReturnValue())
      return (ASTExpression) jjtGetChild(0);
    else return null;
  }

  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=18cfccb14d5082ea0df549fb5e0b87dc (do not edit this line) */
