/* Generated By:JJTree: Do not edit this line. ASTStringTemplate.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

import java.util.LinkedList;
import java.util.List;

public
class ASTStringTemplate extends ASTUserDefined {
  List<StringTemplateElement> elementList = new LinkedList<StringTemplateElement>();

  public List<StringTemplateElement> getElementList() {
    return elementList;
  }
  public void add(StringTemplateElement element) { elementList.add(element); }

  public ASTStringTemplate(int id) {
    super(id);
  }

  public ASTStringTemplate(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efe3b50503735939057c39a54286ae8a (do not edit this line) */
