/* Generated By:JJTree: Do not edit this line. ASTType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTType extends SimpleNode {
  public enum AstTypes {
    CHAR,INT,DOUBLE,BOOLEAN,STRING,USER,VOID,ERROR
  }
  protected AstTypes kind;
  protected String name = null;

  public void setName(String name) { this.name = name; }
  public String getName() { return name; }
  public void setKind(AstTypes kind) { this.kind = kind; }
  public AstTypes getKind() { return kind; }

  public ASTType(int id) {
    super(id);
  }

  public ASTType(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9db2a04b125a4523ac89b30375b525a0 (do not edit this line) */
