/* Generated By:JJTree: Do not edit this line. ASTVariable.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTVariable extends ASTVariableDecl {
  public ASTVariable(int id) {
    super(id);
  }

  public ASTVariable(STMJ p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9f891d3b6914211f8f9d44f7f0c37f49 (do not edit this line) */
