/* Generated By:JJTree: Do not edit this line. ASTVariableUse.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTVariableUse extends ASTExpression {
  String name;
  ASTExpression deref = null;

  public void setDeref(Node n) { deref = (ASTExpression) n; }
  public void setName(String name) { this.name = name; }
  public String getName() {
    return name;
  }
  public ASTExpression getDeref() {
    return deref;
  }

  public ASTVariableUse(int id) {
    super(id);
  }
  public ASTVariableUse(STMJ p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=3c9ab026c8cbbcb312089307efc8b810 (do not edit this line) */
