/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Kap6.Kap6_3_STMJParser;

public
class ASTWhile extends ASTStatement {
  public ASTExpression getCondition() {
    return (ASTExpression) jjtGetChild(0);
  }
  public ASTStatement getStatement() {
    return (ASTStatement) jjtGetChild(1);
  }

  public ASTWhile(int id) {
    super(id);
  }
  public ASTWhile(STMJ p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=e97f82bcae0b72d7b64bc74501a51c1b (do not edit this line) */
