/* Generated By:JavaCC: Do not edit this line. STMJTreeConstants.java Version 5.0 */
package Kap6.Kap6_3_STMJParser;

public interface STMJTreeConstants
{
  public int JJTVOID = 0;
  public int JJTCOMPILATIONUNIT = 1;
  public int JJTSTRINGTEMPLATE = 2;
  public int JJTCLASS = 3;
  public int JJTATTRIBUTE = 4;
  public int JJTMETHOD = 5;
  public int JJTCONSTRUCTOR = 6;
  public int JJTARRAYTYPE = 7;
  public int JJTTYPE = 8;
  public int JJTPARAMETER = 9;
  public int JJTBLOCK = 10;
  public int JJTMETHODBLOCK = 11;
  public int JJTVARIABLE = 12;
  public int JJTEMPTYSTATEMENT = 13;
  public int JJTEXPRSTATEMENT = 14;
  public int JJTIF = 15;
  public int JJTWHILE = 16;
  public int JJTDOWHILE = 17;
  public int JJTRETURN = 18;
  public int JJTASSIGNMENT = 19;
  public int JJTLOGICAL = 20;
  public int JJTCOMP = 21;
  public int JJTARITHMETIC = 22;
  public int JJTSIGN = 23;
  public int JJTNOT = 24;
  public int JJTPRE = 25;
  public int JJTPOST = 26;
  public int JJTARRAYACC = 27;
  public int JJTDEREF = 28;
  public int JJTVARIABLEUSE = 29;
  public int JJTMETHODCALL = 30;
  public int JJTLITERAL = 31;
  public int JJTNEW = 32;
  public int JJTNEWARRAY = 33;


  public String[] jjtNodeName = {
    "void",
    "CompilationUnit",
    "StringTemplate",
    "Class",
    "Attribute",
    "Method",
    "Constructor",
    "ArrayType",
    "Type",
    "Parameter",
    "Block",
    "MethodBlock",
    "Variable",
    "EmptyStatement",
    "ExprStatement",
    "If",
    "While",
    "DoWhile",
    "Return",
    "Assignment",
    "Logical",
    "Comp",
    "Arithmetic",
    "Sign",
    "Not",
    "Pre",
    "Post",
    "ArrayAcc",
    "Deref",
    "VariableUse",
    "MethodCall",
    "Literal",
    "New",
    "NewArray",
  };
}
/* JavaCC - OriginalChecksum=3374b7bc82acabe175a69706a5da9be0 (do not edit this line) */
